# Site settings
title: Jekyll Course Notes Theme
email: brentyi@berkeley.edu
description: "Jekyll theme for CS231n-style course notes."
baseurl: "/jekyll-course-notes"
url: "https://brentyi.github.io"
courseurl: "https://github.com/brentyi/jekyll-course-notes"
# twitter_username: cs231n
# github_username: cs231n
theme_color: "#8c1515"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
jekyll_prettier:
    exclude: ["*.css"]

# Define chapter collection
collections:
  chapters:
    output: true
    permalink: /:path/
defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: chapter
